services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:3000"
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
